version: '2'
services:
#  postgres:
#    image: postgres:9.4
#    restart: always
#    env_file: .env
#    volumes:
#      - postgres-data:/var/lib/postgresql/data/

  app:
    build: ./app/
    env_file: .env
    expose:
      - '8000'
    volumes:
#      - ./app:/app
      - static-data:/static_in_env/static_root/
      - media-data:/static_in_env/media_root/
    command: gunicorn ecommerce2.wsgi:application -b 0.0.0.0:8000

  web:
    build: ./web/
    restart: always
    ports:
      - "80:80"
    volumes:
      - static-data:/static_in_env/static_root/
      - media-data:/static_in_env/media_root/
    volumes_from:
      - app

volumes:
#  postgres-data:
#    driver: local
  static-data:
    driver: local
  media-data:
    driver: local